In [116]:
import numpy as np
import pandas as pd

In [117]:
companies = pd.read_csv("data/igdb_companies.csv")
involved_companies = pd.read_csv("data/igdb_involved_companies.csv")
games = pd.read_csv("data/igdb.csv")
external_games = pd.read_csv("data/igdb_external_games.csv")
developed = pd.read_csv("data/igdb_developed.csv")
steam_lost = pd.read_csv("data/steam_lost.csv", encoding="unicode_escape")

In [118]:
external_games = external_games.query("platform == 'steam'")
df = games.merge(external_games[["game_id", "uid"]], on="game_id", how="inner")
df

,game_id,name,rating,rating_count,category,uid
0,263822,All Alone,0.000000,0,main_game,2557720
1,119025,Pet Puzzle,0.000000,0,main_game,1092080
2,160939,Tiger Tank 59 I: A-Gun MP095,0.000000,0,dlc_addon,1667954
3,137195,River City Girls Zero,0.000000,0,remaster,1851020
4,203546,Meat & Greed,0.000000,0,main_game,2009730
...,...,...,...,...,...,...
108999,204905,Little League World Series Baseball 2022,0.000000,0,main_game,1681890
109000,260221,Smoots Pinball,0.000000,0,main_game,2438210
109001,121481,Tasomachi: Behind the Twilight,0.000000,0,main_game,1015890
109002,4796,de Blob 2,70.169141,17,main_game,563190
109003,213804,Timberman: The Big Adventure,0.000000,0,main_game,2589910

In [119]:
df["uid"] = pd.to_numeric(df["uid"])
df = df.merge(steam_lost, left_on="uid", right_on="AppID", how="inner")
df = df[["game_id","name","rating","rating_count","category","uid"]]
df

,game_id,name,rating,rating_count,category,uid
0,172244,Traphouse Druglord,0.000000,0,main_game,1354510
1,14379,Skara: The Blade Remains,50.000000,0,main_game,274620
2,166859,Plan Z,0.000000,0,main_game,1436280
3,199283,Rift Sweepers,0.000000,0,main_game,1801830
4,535,WildStar,73.384996,25,main_game,376570
...,...,...,...,...,...,...
3623,11667,Dragon Quest XI: Echoes of an Elusive Age,85.499746,100,main_game,742120
3624,41621,Football Manager 2019,90.505255,51,main_game,872790
3625,41621,Football Manager 2019,90.505255,51,main_game,884830
3626,27861,Lost Planet: Extreme Condition - Colonies Edition,62.488923,7,expanded_game,45720
3627,19564,Death Stranding,86.988742,512,main_game,1190460

In [126]:
df = df.merge(developed, on="game_id", how="inner").merge(companies, on="company_id", how="inner")
df.rename(columns={"name_x": "game_name", "name_y": "company_name"}, inplace=True)
df

,game_id,game_name,rating,rating_count,category,uid,company_id,company_name
0,14379,Skara: The Blade Remains,50.000000,0,main_game,274620,7202,8-bit Studio
1,535,WildStar,73.384996,25,main_game,376570,422,Carbine Studios
2,113362,PlanetSide Arena,80.000000,1,main_game,987350,6997,Daybreak Game Company
3,18093,Just Survive,56.031330,8,main_game,295110,6997,Daybreak Game Company
4,36171,Heavy Metal Machines,60.000000,3,main_game,331360,15562,Hoplon
...,...,...,...,...,...,...,...,...
1627,111602,Terrible Beast from the East,60.000000,0,main_game,969880,33134,Sleeping Hero
1628,112099,Gods Remastered,60.000000,1,remaster,628720,18439,Robot Riot
1629,8339,Minecraft: Story Mode,70.229530,80,main_game,376870,58,Mojang Studios
1630,11667,Dragon Quest XI: Echoes of an Elusive Age,85.499746,100,main_game,742120,2161,Armor Project
1631,19564,Death Stranding,86.988742,512,main_game,1190460,170,Kojima Productions

In [132]:
df["company_name"].value_counts().to_csv("final_data/serial_delisters.csv")