In [116]:
import numpy as np
import pandas as pd

In [117]:
companies = pd.read_csv("data/igdb_companies.csv")
involved_companies = pd.read_csv("data/igdb_involved_companies.csv")
games = pd.read_csv("data/igdb.csv")
external_games = pd.read_csv("data/igdb_external_games.csv")
developed = pd.read_csv("data/igdb_developed.csv")
steam_lost = pd.read_csv("data/steam_lost.csv", encoding="unicode_escape")

In [118]:
external_games = external_games.query("platform == 'steam'")
com_df = games.merge(external_games[["game_id", "uid"]], on="game_id", how="inner")
com_df

,game_id,name,rating,rating_count,category,uid
0,263822,All Alone,0.000000,0,main_game,2557720
1,119025,Pet Puzzle,0.000000,0,main_game,1092080
2,160939,Tiger Tank 59 I: A-Gun MP095,0.000000,0,dlc_addon,1667954
3,137195,River City Girls Zero,0.000000,0,remaster,1851020
4,203546,Meat & Greed,0.000000,0,main_game,2009730
...,...,...,...,...,...,...
108999,204905,Little League World Series Baseball 2022,0.000000,0,main_game,1681890
109000,260221,Smoots Pinball,0.000000,0,main_game,2438210
109001,121481,Tasomachi: Behind the Twilight,0.000000,0,main_game,1015890
109002,4796,de Blob 2,70.169141,17,main_game,563190
109003,213804,Timberman: The Big Adventure,0.000000,0,main_game,2589910

In [119]:
com_df["uid"] = pd.to_numeric(com_df["uid"])
com_df = com_df.merge(steam_lost, left_on="uid", right_on="AppID", how="inner")
com_df = com_df[["game_id","name","rating","rating_count","category","uid"]]
com_df

,game_id,name,rating,rating_count,category,uid
0,172244,Traphouse Druglord,0.000000,0,main_game,1354510
1,14379,Skara: The Blade Remains,50.000000,0,main_game,274620
2,166859,Plan Z,0.000000,0,main_game,1436280
3,199283,Rift Sweepers,0.000000,0,main_game,1801830
4,535,WildStar,73.384996,25,main_game,376570
...,...,...,...,...,...,...
3623,11667,Dragon Quest XI: Echoes of an Elusive Age,85.499746,100,main_game,742120
3624,41621,Football Manager 2019,90.505255,51,main_game,872790
3625,41621,Football Manager 2019,90.505255,51,main_game,884830
3626,27861,Lost Planet: Extreme Condition - Colonies Edition,62.488923,7,expanded_game,45720
3627,19564,Death Stranding,86.988742,512,main_game,1190460

In [126]:
com_df = com_df.merge(developed, on="game_id", how="inner").merge(companies, on="company_id", how="inner")
com_df.rename(columns={"name_x": "game_name", "name_y": "company_name"}, inplace=True)
com_df

,game_id,game_name,rating,rating_count,category,uid,company_id,company_name
0,14379,Skara: The Blade Remains,50.000000,0,main_game,274620,7202,8-bit Studio
1,535,WildStar,73.384996,25,main_game,376570,422,Carbine Studios
2,113362,PlanetSide Arena,80.000000,1,main_game,987350,6997,Daybreak Game Company
3,18093,Just Survive,56.031330,8,main_game,295110,6997,Daybreak Game Company
4,36171,Heavy Metal Machines,60.000000,3,main_game,331360,15562,Hoplon
...,...,...,...,...,...,...,...,...
1627,111602,Terrible Beast from the East,60.000000,0,main_game,969880,33134,Sleeping Hero
1628,112099,Gods Remastered,60.000000,1,remaster,628720,18439,Robot Riot
1629,8339,Minecraft: Story Mode,70.229530,80,main_game,376870,58,Mojang Studios
1630,11667,Dragon Quest XI: Echoes of an Elusive Age,85.499746,100,main_game,742120,2161,Armor Project
1631,19564,Death Stranding,86.988742,512,main_game,1190460,170,Kojima Productions

In [132]:
com_df["company_name"].value_counts().to_csv("final_data/serial_delisters.csv")

In [151]:
genres = pd.read_csv("data/igdb_genres.csv")

gen_df = games.merge(external_games[["game_id", "uid"]], on="game_id", how="inner")
gen_df["uid"] = pd.to_numeric(gen_df["uid"])
gen_df = gen_df.merge(steam_lost, left_on="uid", right_on="AppID", how="inner")
#genres_simple = genres.drop_duplicates("game_id")
gen_df = gen_df.merge(genres, on="game_id", how="inner")
gen_df["genre"] = gen_df["genre"].replace(np.NaN, "Unknown")
gen_df

,game_id,name,rating,rating_count,category,uid,Owners,AppID,Name,Type,Changed,Kinguin,Achievements,genre
0,172244,Traphouse Druglord,0.000000,0,main_game,1354510,0.06%,1354510,Traphouse Druglord,Purchase disabled,09/2023,NaN,?,Simulator
1,172244,Traphouse Druglord,0.000000,0,main_game,1354510,0.06%,1354510,Traphouse Druglord,Purchase disabled,09/2023,NaN,?,Strategy
2,172244,Traphouse Druglord,0.000000,0,main_game,1354510,0.06%,1354510,Traphouse Druglord,Purchase disabled,09/2023,NaN,?,Indie
3,14379,Skara: The Blade Remains,50.000000,0,main_game,274620,28.57%,274620,Skara - The Blade Remains,F2P (unavailable),12/2018,1.46,0,Role-playing (RPG)
4,14379,Skara: The Blade Remains,50.000000,0,main_game,274620,28.57%,274620,Skara - The Blade Remains,F2P (unavailable),12/2018,1.46,0,Hack and slash/Beat 'em up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7631,27861,Lost Planet: Extreme Condition - Colonies Edition,62.488923,7,expanded_game,45720,9.75%,45720,Lost Planet: Extreme Condition - Colonies Edition,Purchase disabled,11/2021,NaN,0,Platform
7632,27861,Lost Planet: Extreme Condition - Colonies Edition,62.488923,7,expanded_game,45720,9.75%,45720,Lost Planet: Extreme Condition - Colonies Edition,Purchase disabled,11/2021,NaN,0,Adventure
7633,19564,Death Stranding,86.988742,512,main_game,1190460,20.39%,1190460,DEATH STRANDING,Delisted,11/2022,NaN,63,Shooter
7634,19564,Death Stranding,86.988742,512,main_game,1190460,20.39%,1190460,DEATH STRANDING,Delisted,11/2022,NaN,63,Role-playing (RPG)
7635,19564,Death Stranding,86.988742,512,main_game,1190460,20.39%,1190460,DEATH STRANDING,Delisted,11/2022,NaN,63,Adventure

In [152]:
gen_df["genre"].value_counts()

genre
Indie                         2233
Adventure                     1335
Strategy                       887
Simulator                      801
Role-playing (RPG)             694
Shooter                        306
Sport                          306
Racing                         197
Puzzle                         170
Platform                       123
Arcade                         116
Real Time Strategy (RTS)        73
Turn-based strategy (TBS)       72
Tactical                        55
Card & Board Game               54
Point-and-click                 52
Hack and slash/Beat 'em up      47
Fighting                        45
Visual Novel                    30
Music                           23
Quiz/Trivia                      9
MOBA                             8
Name: count, dtype: int64

In [153]:
gen_df["genre"].value_counts().to_csv("final_data/genres.csv")

In [158]:
gen_df_2 = games.merge(external_games[["game_id", "uid"]], on="game_id", how="inner")
gen_df_2["uid"] = pd.to_numeric(gen_df_2["uid"])
gen_df_2 = gen_df_2.merge(genres, on="game_id", how="inner")
gen_df_2

,game_id,name,rating,rating_count,category,uid,genre
0,263822,All Alone,0.000000,0,main_game,2557720,Adventure
1,263822,All Alone,0.000000,0,main_game,2557720,Indie
2,119025,Pet Puzzle,0.000000,0,main_game,1092080,Simulator
3,160939,Tiger Tank 59 I: A-Gun MP095,0.000000,0,dlc_addon,1667954,Indie
4,137195,River City Girls Zero,0.000000,0,remaster,1851020,Fighting
...,...,...,...,...,...,...,...
230553,4796,de Blob 2,70.169141,17,main_game,563190,Adventure
230554,4796,de Blob 2,70.169141,17,main_game,563190,Indie
230555,213804,Timberman: The Big Adventure,0.000000,0,main_game,2589910,Platform
230556,213804,Timberman: The Big Adventure,0.000000,0,main_game,2589910,Adventure
230557,213804,Timberman: The Big Adventure,0.000000,0,main_game,2589910,Arcade

In [159]:
gen_df_2["genre"].value_counts()

genre
Indie                         75751
Adventure                     44422
Simulator                     25711
Strategy                      23647
Role-playing (RPG)            16790
Puzzle                         6909
Shooter                        5692
Sport                          5490
Platform                       4761
Racing                         4644
Arcade                         4435
Visual Novel                   2118
Turn-based strategy (TBS)      1524
Point-and-click                1522
Fighting                       1328
Tactical                       1276
Hack and slash/Beat 'em up     1247
Real Time Strategy (RTS)       1193
Card & Board Game              1148
Music                           575
Pinball                         169
Quiz/Trivia                     130
MOBA                             76
Name: count, dtype: int64